import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.landingBackground}>
        <div className={styles.framesBackground}></div>

        <div className={styles.loginFrame}></div>

        <div className={styles.loginFrameHeading}>Nitro Manage</div>
        <div className={styles.logo}></div>

        <div className={styles.usernamePromptText}>Username</div>
        <div className={styles.usernameField}></div>
        <div className={styles.usernameFieldIconFrame}>
          <div className={styles.usernameFieldIcon}></div>
        </div>

        {/* <div className={styles.passwordFieldPrompt}>Password</div>
        <div className={styles.passwordField}></div>
        <div className={styles.passwordFieldIconFrame}>
          <div className={styles.passwordFieldIcon}></div>
        </div> */}

        {/* Bottom right login button */}
        <div className={styles.loginButton}></div>
        <div className={styles.loginButtonText}>Login</div>
      </div>
      
      
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
