name: CI/CD

on:
  push:
    branches: [ prod ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.18.0'
          cache: 'yarn'
      - run: corepack enable
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            # Now we have gotten access to EC2 and we will start the deploy .
            cd NITRO30022-Frontend/ &&
            git checkout prod &&
            git pull &&
            yarn dev
          '
