name: Cypress Tests for Nitrus Application

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install Yarn dependencies, cache them correctly
      # and run all Cypress tests on Chrome
      - name: Chrome Nitrus Test
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          build: yarn build
          start: yarn dev
          browser: chrome

      # - name: Firefox Nitrus Test
      #   uses: cypress-io/github-action@v4.2.0 # use the explicit version number
      #   with:
      #     build: yarn build
      #     start: yarn dev
      #     browser: firefox
