name: Cypress Tests for Nitrus Application
#Test7
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout Backend Repo
        uses: actions/checkout@master 
        with:
          token: ${{ secrets.PEP_ACCESS_TOKEN }}
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r NITRO30022-Backend/requirements.txt

      - name: Set up env variables
        run: |
          touch .env
          echo MONGO_DB_USERNAME=pablol >> .env
          echo MONGO_DB_PASSWORD=zhOEdo3dNhScqTEA >> .env
          echo MONGO_DB_HOST=cluster0.n3en270.mongodb.net >> .env
      
      - name: Run Backend Server
        run: |
          python manage.py runserver

      # Install Yarn dependencies, cache them correctly
      # and run all Cypress tests on Chrome
      - name: Chrome Nitrus Test
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          build: yarn build
          start: yarn dev
          browser: chrome

      # - name: Firefox Nitrus Test
      #   uses: cypress-io/github-action@v4.2.0 # use the explicit version number
      #   with:
      #     build: yarn build
      #     start: yarn dev
      #     browser: firefox
