name: Cypress Tests for Nitrus Application
#Test4
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run backend
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with: 
          owner: EfficientBogoSort
          repo: NITRO30022-Backend
          github_token: ${{ secrets.PEP_ACCESS_TOKEN }}
          workflow_file_name: testing2.yml
          ref: develop


      # Install Yarn dependencies, cache them correctly
      # and run all Cypress tests on Chrome
      - name: Chrome Nitrus Test
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          build: yarn build
          wait-on: 'http://localhost:8081'
          start: yarn dev
          browser: chrome

      # - name: Firefox Nitrus Test
      #   uses: cypress-io/github-action@v4.2.0 # use the explicit version number
      #   with:
      #     build: yarn build
      #     start: yarn dev
      #     browser: firefox
