name: Cypress Tests for Nitrus Application
#Test7
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Checkout Backend Repo
      #   uses: actions/checkout@master 
      #   with:
      #     token: ${{ secrets.PEP_ACCESS_TOKEN }}
      #     submodules: true
          
      # Install Yarn dependencies, cache them correctly
      # and run all Cypress tests on Chrome
      - name: Chrome Nitrus Test
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          build: yarn build
          start: yarn start
          browser: chrome
          headed: true
          record: true
          spec: cypress/e2e/Nitrus-Tests/nitrus.cy.js
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Firefox Nitrus Test
      #   uses: cypress-io/github-action@v4.2.0 # use the explicit version number
      #   with:
      #     build: yarn build
      #     start: yarn dev
      #     browser: firefox
